#.streamlit/secrets.toml 
#database infomation
#ref: https://docs.streamlit.io/develop/tutorials/databases/mssql


server = "localhost\\SQLEXPRESS"
database = "EventDB"
username = "eventdb_admin"
password = "1234"
